theme: jekyll-theme-minimal
title: WDSS Student Speaker Series
description: "At WDSS, we think that it's important for students to have the opportunity to share their learnings in data science with the rest of the community. Be this a project you've worked on, a new technique you've learned, or an opportunity you wish to share, the WDSS Student Speaker Series is your chance to give a short talk to the society to share your love of data science."
logo: logo.jpg
